# Project information
site_name: LibAAA
site_description: LibAAA is a cross platform radius (AAA) protocol library written in C99 with C++ bindings.
site_author: Ludwig Fuechsl
copyright: >- 
  &copy; Copyright 2023 Moxibyte GmbH<br/>
  <br/>
  <a href="https://moxibyte.com/imprint.html" target="_blank">Impressum</a> | 
  <a href="https://moxibyte.com/datenschutz.html" target="_blank">Datenschutzerklärung</a>

# GitHub repository link
repo_url: https://github.com/moxibyte/libaaa
edit_uri: blob/main/documentation

# TODO: Deploy options

# File locations
docs_dir: docs

# Navigation
nav:
  - About: "index.md"
  - LibAAA: 
    - About: "libaaa/index.md"
    - libaaa_pg:
      - Reference: "libaaa/libaaa_pg/reference.md"
      - User Guide: "libaaa/libaaa_pg/guide.md"
      - Example: "libaaa/libaaa_pg/example.md"
    - libaaa_pr:
      - Reference: "libaaa/libaaa_pr/reference.md"
      - User Guide: "libaaa/libaaa_pr/guide.md"
      - Example: "libaaa/libaaa_pr/example.md"
    - "libaaa::packet_generator":
      - Reference: "libaaa/packet_generator/reference.md"
      - User Guide: "libaaa/packet_generator/guide.md"
      - Example: "libaaa/packet_generator/example.md"
    - "libaaa::packet_reader":
      - Reference: "libaaa/packet_reader/reference.md"
      - User Guide: "libaaa/packet_reader/guide.md"
      - Example: "libaaa/packet_reader/example.md"
  - LibAAA-Server: "libaaa-server/index.md"
  - LibAAA-Client: "libaaa-client/index.md"

# Markdown extensions
markdown_extensions:
  # Checked list
  - pymdownx.tasklist:
      custom_checkbox: true
  # Code hilight
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Footnotes
  - footnotes
  # admonition (Alerts)
  - admonition
  - pymdownx.details
  # Icons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Annotations
  - md_in_html

# Visual customisation
theme:
  name: material
  
  # Customize
  icon:
    logo: material/key
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

  # Light and Dark mode
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Cookie consent
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
