name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  test_linux:
    name: Unit Test (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Install requirements
      working-directory: $libaaa/test
      run: pip install -r ./requirements.txt
    - name: Build application
      working-directory: $/libaaa/test
      run: python ./build.py
    - name: Run Unittest
      working-directory: $/libaaa/test/build
      run: ./libaaa_test
     
 #  test_windows:
 #    name: Unit Test (Linux)
 #    needs: test_linux
 
